name: Deploy ASP.NET Core Web Application to recipe-api-host
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: recipe-api-host
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.RECIPE_API_HOST_PUBLISH_PROFILE }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.100-rc.2.20479.15
  PROJECT_PATH: RecipeApi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore packages
      run: dotnet restore "${{ env.PROJECT_PATH }}" -r win-x86
    - name: Build app
      run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore -r win-x86
    - name: Test app
      run: dotnet test "${{ env.PROJECT_PATH }}" --no-build
    - name: Publish app for deploy
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" --self-contained -r win-x86
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Import API into Azure API Management
      run: |
        az apim api import --specification-format Swagger --subscription-required false --path "recipes/v1" --resource-group RecipeApiGroup --service-name recipe-apis --api-id RecipeApi --service-url "https://recipe-api-host.azurewebsites.net" --specification-path "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/swagger.json"
        
      
